name = "Epi-Life"
license = "MIT"
licenselink = "https://github.com/gurusabarish/hugo-profile/blob/master/LICENSE"
description = "Life and Medicine"
homepage = "https://github.com/Keyong-bio/MYBLOG"
demosite = "https://hugo-profile.netlify.app"
tags = ["Responsive","Blog", "Portfolio", "Personal"]
min_version = "0.68.0"

[author]
  name = "Keyong"
